name: CI/CD Docker

on:
    push:
        branches: [main]
env:
    DOCKER_IMAGE: ghcr.io/mathegod/my_2nd_project
    VERSION: ${{ github.sha }}

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Check out source code
              uses: actions/checkout@v2

            - run: npm ci
            - run: npm run build --if-present
            - run: npm test

            - name: Set up docker buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - name: Cache docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ env.VERSION }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: mathe1303/practice-ci-cd:latest

    deploy:
        needs: build
        name: Deploy
        runs-on: [self-hosted, label-go]
        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}
            - name: Docker run
              run: |
                  docker ps -q --filter "name={your image name}" | grep -q . && docker stop {your image name} && docker rm -fv {your image name}
                  docker run -d -p 8080:8080 --name cicd --restart always ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
