name: Node.js CI/CD

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - run: npm ci
            - run: npm run build --if-present
            - run: npm test

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: mathe1303/practice-ci-cd:latest

            - name: Install SSH client
              run: sudo apt-get update && sudo apt-get install -y openssh-client

            - name: Deploy to EC2 instance
              uses: easingthemes/ssh-deploy@v2
              with:
                  server: ${{ secrets.SERVER_IP }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      # Stop and remove existing container
                      sudo docker stop my-container || true
                      sudo docker rm my-container || true

                      # Pull the latest image
                      sudo docker pull mathe1303/practice-ci-cd:latest

                      # Run the container
                      sudo docker run -d --name my-container -p 80:3000 mathe1303/practice-ci-cd:latest
